application: pcd-homework-h3
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /History.php
  script: History.php

- url: /Mail.php
  script: Mail.php

- url: .*
  script: main.php
